In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime

# Optional: Candlestick chart
import plotly.graph_objects as go

In [11]:
FILE_PATH = "output/ADANIPOWER_NS.min_csv"

In [12]:
df = pd.read_csv(FILE_PATH)
df.head()

,date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Datetime
0,2025-09-05 09:15:00,121.430008,121.709999,120.809998,121.409996,121.409996,17313,0.0,0.0,2025-09-05 09:15:00+05:30
1,2025-09-05 09:17:00,121.349998,121.449997,121.240005,121.369995,121.369995,31120,0.0,0.0,2025-09-05 09:17:00+05:30
2,2025-09-05 09:19:00,121.360001,121.400002,121.190002,121.199997,121.199997,20243,0.0,0.0,2025-09-05 09:19:00+05:30
3,2025-09-05 09:21:00,121.219994,121.219994,121.099998,121.130005,121.130005,19939,0.0,0.0,2025-09-05 09:21:00+05:30
4,2025-09-05 09:23:00,121.040001,121.080002,120.840004,121.080002,121.080002,26280,0.0,0.0,2025-09-05 09:23:00+05:30